name = "RayJL"
uuid = "d257e7ad-0399-4729-ab27-f264e306a93c"
authors = ["bryan <bryan.deng002@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
