function print_image(image::Array{Color})
    CHARS = ".:-=+*#%@"
    for i = 1:size(image, 1)
        for j = 1:size(image, 2)
            ind = Int(round(grayscale(image[i, j]) / 255 * (length(CHARS) - 1) + 1))
            print(CHARS[ind])
        end
        println()
    end
end

function write_ppm(image::Array{Color}, filename::String; format::String="P6")
    open(filename, "w") do io
        if format != "P6" && format != "P3"
            error("format must be P6 or P3")
        end

        write(io, "# Generated by RayJL\n")
        write(io, "$format $(size(image, 2)) $(size(image, 1)) 255\n")

        if format == "P6"
            for i = 1:size(image, 1)
                for j = 1:size(image, 2)
                    write(io, image[i, j].r)
                    write(io, image[i, j].g)
                    write(io, image[i, j].b)
                end
            end
        else
            for i = 1:size(image, 1)
                for j = 1:size(image, 2)
                    write(io, "$(image[i, j].r) $(image[i, j].g) $(image[i, j].b)\n")
                end
            end
        end
    end
end
